### ISSUE TITLE
🔖 Meta: `0.1.0` Checklist

### ISSUE THREAD

**Issue by pcaversaccio** [pcaversaccio/snekmate#221]
## 📋 🐍 snekmate `0.1.0` Checklist

> [!IMPORTANT]
> The aggregating PR used to implement the full checklist is https://github.com/pcaversaccio/snekmate/pull/207.

- [x] Authentication
  - [x] `ownable` (#218)
  - [x] `ownable_2step` (#219)
  - [x] `access_control` (#216)
- [x] Extensions
  - [x] `erc2981` (#233)
  - [x] `erc4626` (#236)
- [x] Governance
  - [x] `timelock_controller` (#220)
- [x] Tokens
  - [x] `erc20` (#234)
  - [x] `erc721` (#237)
  - [x] `erc1155` (#238)
- [x] Utility Functions
  - [x] `base64` (#222)
  - [x] `batch_distributor` (#223)
  - [x] `create_address` (#224)
  - [x] `create2_address` (#225)
  - [x] `ecdsa` (#227)
  - [x] `message_hash_utils` (#227)
  - [x] `signature_checker` (#228)
  - [x] `eip712_domain_separator` (#229)
  - [x] `math` (#230)
  - [x] `merkle_proof_verification` (#231)
  - [x] `multicall` (#232)
- [x] Miscellaneous
  - [x] Use `snake_case` notation for module and mock contracts. (#242)
  - [x] Add documentation on how to use 🐍 snekmate contracts as modules. (#247)
  - [x] Add the following new features to 🐍 snekmate:
    - [x] #175 (#243),
    - [x] #184 (#239),
    - [x] #180 (#240).
